Stats over time (WIP)
GTBitsOfGood/helping-mamas pull request #206
Opened 2022-11-29 18:20 UTC by ShmulTomer

Making progress but still have work to do on this (I can probably have it done by late tonight)

2022-12-01 06:47 UTC, jwu6492 commented
@ShmulTomer you might be able to reference my changes on `StatDisplay.jsx` and see if that can help you

2022-12-02 03:18 UTC, YiQin93 commented
I loved the date range selector!! It looks very elegant!! A medal for all of you 🥇 :)

**About the event history table.** 
It has the following issues:

1. It would be great if we could add a title for it, named "Event History" and be left-aligned at the top of the table.

2. For the table's header:
- Expected: "Event Name", "Date", "Time", and "Attendance"
- What it has: the current header is for the Volunteers database/list.

3. For the content on the table
- Expected: the event's name, date, time span, the number of volunteers who participated, and a "View Event Page" button.
- What it has: the event's name, date & time but in a hard-to-read format.

Since it looks like it will take some time to make these changes, I would like your opinions. We can either:

A. Fix all three points above and make it look like the design.

B. Remove the Event History table for this deployment, but keep the code, and we will fix it next semester.

This table is a nice-to-have feature. It makes it easy for users to review previous events over a period of time, as well as understand which event contributes the most/least hours of work. It would work best with everything arranged and labeled. 

Therefore, I would love to know your capacity in this. If you do not have sufficient time or just do not want to work on it now, we will choose option B!

Let me know!

**Another small thing:**
It would be great if we could left-aligned the header "Statistics". It is currently at the center. Keeping the same alignment makes it easier for the users to find information!

2022-12-02 11:43 UTC, ShmulTomer commented
Hey Yi! Thank you for the feedback! I'm currently on a blocker for the backend of this screen, that if I can fix today then also finishing the front end will be no big deal. I'm keeping up with Colin on this as well

2023-02-03 16:20 UTC, colin4554 requested changes
Let me know if you have any questions

2023-02-03 16:20 UTC, colin4554 commented on src/pages/api/attendance/eventstatistics.ts
> +    // var groupBy = function(xs, key) {
Please delete any comments we don't need

2023-02-03 16:20 UTC, colin4554 commented on src/actions/queries.js
> +export const getEventStatistics = () =>
Why does this not take a start and end date anymore? On the mongo side, you should be able to easily filter the attendance objects by checkIn with something like: `{checkedIm:{$gte:startDate,$lt:endDate}`

2023-02-03 16:20 UTC, colin4554 commented on src/actions/queries.js
> +export const getSimpleAttendanceForEvent = (eventId) =>
Please remove any functions we aren't using (on both the front and back end)

2023-02-03 16:20 UTC, colin4554 commented on src/pages/api/users/stats.js
> +    else attendances = await getAllAttendanceObjects(next);
Not sure if this was you or Jonathan, but we should just return an empty list if a userId isn't passed

2023-02-04 21:30 UTC, YiQin93 commented
Overall it looks fantastic! I am so glad that this finally worked out!!!

There seem to be some issues with the calculation of participated hours. For example,
- In steps [#94](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/94/Comments) to [#97](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/97/Comments) in this report: (https://go.playerzero.app/share/63decbb12b1d69c0be54997a), there is a Yi has a "-1 hour" participation, but her check-in time is 16:17 and her check-out time is 19:00, which should be 2.72 hours.
- In the screenshot below, I changed Yi's check-out time to 13:00, but the hours participated displayed a positive number 3.285.
![image](https://user-images.githubusercontent.com/65053210/216790326-3ea69ac3-d393-4a71-9967-11b9c47190bb.png)

2023-02-05 14:42 UTC, ShmulTomer commented
> Overall it looks fantastic! I am so glad that this finally worked out!!!
> 
> There seem to be some issues with the calculation of participated hours. For example,
> 
> * In steps [#94](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/94/Comments) to [#97](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/97/Comments) in this report: (https://go.playerzero.app/share/63decbb12b1d69c0be54997a), there is a Yi has a "-1 hour" participation, but her check-in time is 16:17 and her check-out time is 19:00, which should be 2.72 hours.
> * In the screenshot below, I changed Yi's check-out time to 13:00, but the hours participated displayed a positive number 3.285.
>   ![image](https://user-images.githubusercontent.com/65053210/216790326-3ea69ac3-d393-4a71-9967-11b9c47190bb.png)

I definitely see a few issues! Sadly I can't get to it today but I can try for tomorrow -> I think the issues extend past the stats-over-time screen so I'm not sure it'll be a quick fix

2023-02-07 02:01 UTC, colin4554 commented
> Overall it looks fantastic! I am so glad that this finally worked out!!!
> 
> There seem to be some issues with the calculation of participated hours. For example,
> 
> * In steps [#94](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/94/Comments) to [#97](https://go.playerzero.app/share/63decbb12b1d69c0be54997a/devtools/97/Comments) in this report: (https://go.playerzero.app/share/63decbb12b1d69c0be54997a), there is a Yi has a "-1 hour" participation, but her check-in time is 16:17 and her check-out time is 19:00, which should be 2.72 hours.
> * In the screenshot below, I changed Yi's check-out time to 13:00, but the hours participated displayed a positive number 3.285.
>   ![image](https://user-images.githubusercontent.com/65053210/216790326-3ea69ac3-d393-4a71-9967-11b9c47190bb.png)

@YiQin93 This is an existing issue. I already have a ticket to standardize data/time and will add a note about this issue there. It looks like we could easily prevent it by only allowing the check-out time to be in the future (and the check-in time in the past) when admins edit time cards.

2023-02-07 18:40 UTC, colin4554 approved these changes

2023-02-07 19:30 UTC, merged