Eventshifts
GTBitsOfGood/helping-mamas pull request #22
Opened 2021-10-05 21:10 UTC by shwetamurali

## PR Title/Tagline

Add event shifts in order to create a new object separate from the event

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

### Important Changes

- Database change
- Changed frontend form input

### Related Github Issues

- #7 

### Related PRs

- #PRNUMBER

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

2021-10-13 20:45 UTC, azeng8100 commented on backend/src/models/event.js
> +    max_shifts: {
What is max shifts for?

2021-10-13 20:52 UTC, azeng8100 requested changes
Steps to recreate a bug:

1. Create two shifts and fill them in w/ random values
2. Create another shift that's empty
3. Delete the 2nd shift

Expected behavior: 2nd filled in shift is deleted. Left with 1st filled in shift and an empty shift
Bug: 2nd filled in shift is not deleted, empty shift is gone

Also can be replicated with deleting the first shift

2021-10-18 13:48 UTC, vpatakottu commented on backend/src/models/event.js
> +    max_shifts: {
I just realized I forgot to push the changes in the backend folder 😅. That should be deleted now!

2021-10-21 00:12 UTC, azeng8100 commented
Bug 2: Cannot delete multiple events
I created 3 events and deleted 1 event. I was unable to delete another event since the "Delete" button is faded/unclickable
![image](https://user-images.githubusercontent.com/52008605/138188974-98d35450-a28a-4c30-8a2a-3dd45000d9ae.png)

Bug 3: Cannot see edit after submitting
Initial view:
![image](https://user-images.githubusercontent.com/52008605/138189196-c8c0b25a-efd6-48c5-9ecf-7fc4d30ccb1c.png)
Properly updated in database:
![image](https://user-images.githubusercontent.com/52008605/138189213-d69d5284-7c17-47a5-a17a-ed93950cabde.png)
Cannot see new email after hitting edit again
![image](https://user-images.githubusercontent.com/52008605/138189235-fde608a0-0b0c-4227-8a32-8b9da3187706.png)

Missing feature: Cannot edit shifts
1. We can remove max_shifts from here
2. Cannot view existing shifts and change their time
![image](https://user-images.githubusercontent.com/52008605/138189051-bbefa08b-116c-4b6d-800e-b4928248bfc6.png)

2021-12-11 02:32 UTC, Arisusu approved these changes

2021-12-11 02:32 UTC, merged