Improve Login/Signup Experience
GTBitsOfGood/helping-mamas pull request #237
Opened 2023-02-02 03:01 UTC by bphoebew

Improving the design of login/signup pages

2023-02-03 16:00 UTC, colin4554 requested changes

2023-02-03 16:00 UTC, colin4554 commented on src/screens/Auth/helpers.js
> +export const validationSchema = yup.object({
What is validationSchema for?

2023-02-03 16:00 UTC, colin4554 commented on src/screens/Auth/helpers.js
>    // .matches(/[a-zA-Z]/, "Password can only contain Latin letters."),
Please remove any comments we don't need

2023-02-03 16:02 UTC, colin4554 commented
@YiQin93 Can we remove/change the placeholder text in the fields? I'm not sure that the current placeholder text adds anything. It would probably make the most sense to either remove it or make it better (ie `jsmith@outlook.com` for the email placeholder)

2023-02-03 18:43 UTC, YiQin93 commented
> @YiQin93 Can we remove/change the placeholder text in the fields? I'm not sure that the current placeholder text adds anything. It would probably make the most sense to either remove it or make it better (ie `jsmith@outlook.com` for the email placeholder)

Yeah sure!! The current placeholder "Example@email.com" makes sense!!! Thanks for catching this~~ :)

2023-02-04 04:02 UTC, YiQin93 commented
This is very neat and user-friendly! It looks awesome!

There are two small issues:
1. Keeping the wording consistent could be very beneficial for users to digest information. For consistency, it would be wonderful if we could make the following changes:
- change the text pointed by the 1st arrow from "Create an account" to "Create an Account"
- change the text pointed by the 2nd arrow from "Sign up with Google" to "Continue with Google"
- change the text pointed by the 3rd arrow from "Sign up" to "Create an account"
- change the text pointed by the 4th arrow from "Sign in" to "Sign In"
(It would be even better if we could also pay attention to the capitalization!)
![image](https://user-images.githubusercontent.com/65053210/216746616-c1eee725-8b0a-422b-b72e-1f427a3c40d5.png)

2. The error message for passwords with only numbers is somewhat confusing. Can we please change it to "Password should at least contain 1 letter"?
![image](https://user-images.githubusercontent.com/65053210/216746282-9232c928-9fc5-406d-a5eb-a4e730bdc516.png)

2023-02-04 13:18 UTC, YiQin93 commented
This looks great!!! Thanks Phoebe for fixing it right away! Their Login/Signup experience has been largely improved :)

2023-02-06 19:41 UTC, colin4554 approved these changes

2023-02-06 19:42 UTC, merged