Unregister Popup Confirmation
GTBitsOfGood/helping-mamas pull request #263
Opened 2023-02-16 16:56 UTC by bphoebew

2023-02-20 20:15 UTC, colin4554 requested changes

2023-02-20 20:15 UTC, colin4554 commented on src/pages/events/[eventId]/EventUnRegisterModal.jsx
> +import { useState } from "react";
This file should be under the components folder. Right now it is being treated like a page.

2023-02-20 20:15 UTC, colin4554 commented on src/pages/events/[eventId]/index.js
> -                  Unregister
I would leave this text as is

2023-02-20 20:15 UTC, colin4554 commented on src/pages/events/[eventId]/EventUnRegisterModal.jsx
> +        <Button color="primary" onClick={handleSubmit} disabled={isDeleting}>
Please update all the variables like isDeleting and text like Delete Entry so they make sense for the unregister flow

2023-02-21 02:34 UTC, YiQin93 commented
This looks fantastic!

2023-02-21 15:18 UTC, colin4554 approved these changes

2023-02-21 15:20 UTC, merged