Initial PR
GTBitsOfGood/helping-mamas pull request #274
Opened 2023-02-23 01:34 UTC by ShmulTomer

### PR Title

One liner about what this PR changes and why

#### Dev Checklist
- [ ] If there was a database change, did you create an upgrade script.
- [ ] Did you link the related github issue(s)?
- [ ] Did you list any known issues/questions with the PR?

2023-03-06 21:29 UTC, YiQin93 commented
This is awesome! Very impressive!! Let's remind ourselves to add error checks/messages as the front-end is implemented.

2023-03-22 22:36 UTC, ShmulTomer commented
edited initial message w/ current progress

2023-03-28 01:09 UTC, YiQin93 commented
Can't say how much I love this look and feel!! 

I think the default values for event creation are not synced to the actual create an event feature. Having a popup notification as the page is saved would also be wonderful. But other than these, this page is wonderful!!!! Thank you so much for your amazing work!

2023-03-28 22:39 UTC, colin4554 requested changes

2023-03-28 22:39 UTC, colin4554 commented on src/utils/mailersend-email.ts
> +
This is incorrectly calling frontend api instead of just the backend function

2023-03-28 23:05 UTC, ShmulTomer commented
almost done; light blue theme gives an error

2023-03-30 00:26 UTC, merged