add past events page
GTBitsOfGood/helping-mamas pull request #42
Opened 2022-02-08 06:08 UTC by shwetamurali

## PR Title/Tagline

What does this PR change and why?

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

### Important Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related Github Issues

- #[Number of Issue]
- Or, remember to link to an issue on the sidebar

### Related PRs

- #PRNUMBER

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

2022-02-09 16:35 UTC, abhigyank requested changes

2022-02-09 16:35 UTC, abhigyank commented on src/components/Header.jsx
> +                selected={currPageMatches("/events")}
Correction: `selected={currPageMatches("/past-events")}`

2022-02-09 16:35 UTC, abhigyank commented on src/screens/Events/User/EventTable.jsx
> -                </td>
Needs to be kept. I guess this was the temporary change for viewing volunteer view?

2022-02-09 16:35 UTC, abhigyank commented on src/screens/Events/index.jsx
> -  props.isAdmin || IS_ADMIN ? <AdminEventManager /> : <UserEventManager />;
Same as above: Needs to be kept. I guess this was the temporary change for viewing volunteer view?

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/index.jsx
> +  <UserEventManager />;
`props.isAdmin || IS_ADMIN ? <AdminEventManager /> : <UserEventManager />;`

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +    fetchEvents()
We need to fetch past events before today, so need to pass an end date to the function. `fetchEvents(undefined, new Date().toLocaleDateString("en-US"))`

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +import EventDeleteModal from "./EventDeleteModal";
Can remove these as we wont require to create, edit or delete event from the past-events page.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +  const [showCreateModal, setShowCreateModal] = useState(false);
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +  };
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +  const [showEditModal, setShowEditModal] = useState(false);
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +  const [showDeleteModal, setShowDeleteModal] = useState(false);
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +  };
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +        </Styled.Button>
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +        onDeleteClicked={onDeleteClicked}
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventManager.jsx
> +      />
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventTable.jsx
> +                onDeleteClicked={onDeleteClicked}
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventTable.jsx
> +  onDeleteClicked: PropTypes.func,
Can remove.

2022-02-09 16:35 UTC, abhigyank commented on src/screens/PastEvents/Admin/EventTableRow.jsx
> +      </td>
Can remove.

2022-02-09 17:31 UTC, shwetamurali commented on src/screens/Events/User/EventTable.jsx
> -                </td>
adding this back gives an error - the user ID is undefined

2022-02-09 17:36 UTC, abhigyank commented on src/screens/Events/User/EventTable.jsx
> -                </td>
Probably need to update the .env file that Jack has updated to support user logins. (It works for me with that, so should be fine to add back I guess).

2022-02-09 17:37 UTC, abhigyank commented on src/screens/Events/User/EventTable.jsx
> -                </td>
Or could be because, this branch doesn't have the changes Jack pushed in for fixing the auth.

2022-02-13 19:06 UTC, merged

2022-02-13 19:06 UTC, abhigyank commented
Merged, good work @shwetamurali! Thanks :rocket: