create upcoming events view
GTBitsOfGood/helping-mamas pull request #52
Opened 2022-02-20 07:41 UTC by jwu6492

## PR Title/Tagline

What does this PR change and why?

### How to Test

1. Please add or build upon a testing card to the [Notion page](http://notion.so) and link it here

### Important Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related Github Issues

- #48 
- Or, remember to link to an issue on the sidebar

### Related PRs

- #PRNUMBER

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

2022-02-20 18:58 UTC, jackpalaia approved these changes

2022-02-21 03:01 UTC, abhigyank requested changes
Require some CSS changes to center divs.

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventManager.jsx
>      width: 95%;
`width: 60%;`

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventManager.jsx
> +    padding-right: 5rem;
replace:
```diff
-    margin-bottom: 1rem;
-    padding-right: 5rem;
+    margin: 0 auto;

```

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventManager.jsx
> +    width: 100%;
width: 60%

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventManager.jsx
> +    margin-left: 10rem;
`margin: 0 auto;`

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventManager.jsx
> +    width: 75%;
width: 78%

2022-02-21 03:01 UTC, abhigyank commented on src/screens/Events/User/EventTable.jsx
> +                  <Table.EventName>{event.name}</Table.EventName>
#51 will update this to `event.title`, so we can change it here.

2022-02-22 17:31 UTC, merged

2022-02-22 17:31 UTC, abhigyank commented
Merged, thanks @jwu6492 :rocket: